Snouter #2
lovretomic/Internship-19-Snouter pull request #1
Opened 2023-05-03 19:11 UTC by lovretomic

**Updated Snouter app:**
- implemented model validation
- included cancellation logic
- added JWT token generation
- added authentication and authorization logic

2023-05-05 09:52 UTC, dariomrk requested changes
- Small changes requested regarding `CancellationToken` support.
- A few suggestions regarding additional properties.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/.idea/.idea.Snouter/.idea/codeStyles/codeStyleConfig.xml
The `./idea` directory should probably be ignored by git.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Identity.Api/Controllers/IdentityController.cs
> +    private const string TokenSecret = "E6JUrU1wdqOpv35T4hUD";
Since you are storing the secret key in the `appsettings` configuration file anyway, you could extract it from there instead of hard coding it here.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Database/DbInitializer.cs
> +                Longitude INTEGER
What [geodetic system](https://en.wikipedia.org/wiki/Geodetic_datum) are you using? I am not aware of any that use a whole number to represent latitude / longitude.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Models/Item.cs
> +    public string? ImageLinks { get; set; }
This implies that one item can only have one image?

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Models/Item.cs
> +    public string? AdditionalProps { get; set; }
Since you are using PostgreSQL (with Npgsql), I would suggest using the `JsonDocument` type for this column as per the [documentation](https://www.npgsql.org/efcore/mapping/json.html#jsondocument-dom-mapping).

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Models/Subcategory.cs
> +    public string? AdditionalProps { get; set; }
Same as in previous comment (use `JsonDocument` type).

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Repositories/CategoryRepository.cs
> +    public async Task<Category> GetByNameAsync(string name)
You could add `CancellationToken` support here.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Repositories/ICategoryRepository.cs
>      Task<Category> GetByNameAsync(string name);
Add `CancellationToken`.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Repositories/ISubcategoryRepository.cs
>      Task<Subcategory> GetByNameAsync(string name);
Add `CancellationToken` support.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Repositories/UserRepository.cs
> +        using var connection = await _dbConnectionFactory.CreateConnectionAsync();
You can pass the token to `CreateConnectionAsync`.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Repositories/UserRepository.cs
> +        using var connection = await _dbConnectionFactory.CreateConnectionAsync();
Add `CancellationToken` support.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Services/CategoryService.cs
> +    public async Task<Category> GetByNameAsync(string name)
Add `CancellationToken` support.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Services/ICategoryService.cs
> +    Task<Category> GetByNameAsync(string name);
Add `CancellationToken` support.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Services/ISubcategoryService.cs
> +    Task<Subcategory> GetByNameAsync(string name);
Add `CancellationToken` support.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Application/Services/SubcategoryService.cs
> +    public async Task<Subcategory> GetByNameAsync(string name)
Add `CancellationToken` support.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Contracts/Requests/CreateItemRequest.cs
> +    public string? AdditionalProps { get; set; }
You can use the `JsonObject` type to correctly generate Swagger docs.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Contracts/Requests/CreateSubcategoryRequest.cs
> +    public string? AdditionalProps { get; set; }
You can use the `JsonObject` type to correctly generate Swagger docs.

2023-05-05 09:52 UTC, dariomrk commented on Snouter/Snouter.Contracts/Responses/SubcategoryResponse.cs
> +    public string? AdditionalProps { get; set; }
`JsonObject` could be used here as well.

2023-05-06 00:35 UTC, JosipaSaravanja approved these changes
The code is working properly. However, there are some recommended changes that are not necessary such as ignoring the ".idea" folder, adding a Guid Id to Categories and SubCategories, using a more precise number format for longitude and latitude, and adding a seed for better data consistency. Also, architecture of solution is a bit unusual (Identity.Id). Overall, I will validate these changes since the code is functional but I highly recommend implementing these improvements in the future.

2023-07-28 19:13 UTC, closed without merging